##Config
alias mount="sudo mount"
alias diff="diff -y"
alias pip="python -m pip" #change made by pip themselves
alias spip="sudo python -m pip" #change made by pip themselves
alias service="sudo systemctl"
alias chmodit="chmod +x"
alias conkyc="vi ~/.conkyrc"
alias zshr="source ~/.zshrc"
alias zshc="vi ~/.zshrc"
alias aliases="vi /home/rl1k/.oh-my-zsh/custom/aliases.zsh"
alias cmd32="wine /home/rl1k/.wine/drive_c/windows/system32/cmd.exe"
alias cmd="wine /home/rl1k/.wine/drive_c/windows/syswow64/cmd.exe"
alias myip="curl ipinfo.io"
alias web="sudo python2 -m SimpleHTTPServer 80"
alias web8000="python -m http.server 8000"
alias smtpserver="python2 -m smtpd -n -c $1 :25"
alias open="xdg-open"
alias vimrc="vi /home/rl1k/.vimrc"
alias vimrcroot_="sudo vi /root/.vimrc"
alias tmuxconf="vi /home/rl1k/.tmux.conf"
alias se="systemctl enable"
alias ss="systemctl start"
alias stop_service="systemctl stop"
alias start_docker="systemctl start docker.service"
alias sshs="systemctl start sshd"
alias port="sudo netstat -antp"
alias portall="sudo netstat -antpu"
alias pvpn="sudo protonvpn"

#bash command
alias del="rm -rf "
alias size="du -hs "
alias .="cd .."
alias ..="cd ../../"
alias ...="cd ../../../"
alias rm="rm -v"
alias ifconfig+='ip addr | grep UP | cut -f2 -d":"'
alias :q="exit"
alias :x="exit"
alias :q!="exit"
alias update="sudo pacman -Syyu --overwrite \"*\" && yay && notif-success 'UPDATE FINISH'"
alias updatedb="sudo updatedb"
alias pac="sudo pacman -S"
alias pacs="sudo pacman -Ss"
alias pacu="sudo pacman -Syy"
alias pacr="sudo pacman -Rns"
alias yayr="yay -Rns"
alias gc="git clone"
alias gc+="sudo git clone"
alias ga.="git add ."
alias ga="git add"
alias gcm="git commit -m"
alias gpo="git push origin"
alias gp="git push"
alias gpu="git push upstream"
alias gpul="git pull"


#Basics tools
alias tryhackme_vpn="sudo openvpn ~/Pentest_Lab/TryHackMe/rl1k.ovpn" 
alias burp_chrome="burp&;  ~/.local/autochrome/chrome-wrapper&"
alias sqlmap="sqlmap --random-agent"
alias bettercap="sudo bettercap"
alias bettercapui="sudo bettercap -caplet http-ui"
alias teamserver="sudo ./teamserver"
alias cobaltstrike="sudo cobaltstrike"
alias nc="ncat"
alias lbzip="lbzip2 -v"
alias bunzip="bunzip -v"
alias googli="google-chrome --incognito"
alias google="google-chrome"
alias ytn="youtube-dl -f bestvideo+bestaudio --cookies=~/Documents/cookies_youtube_rl1k.txt"
alias yts="youtube-dl --write-auto-sub --cookies=~/Documents/cookies_youtube_rl1k.txt --skip-download"
alias yts2="youtube-dl --write-auto-sub --cookies=~/Documents/cookies_youtube_pj.txt --skip-download"
alias yts3="youtube-dl --write-auto-sub --cookies=~/Documents/cookies_youtube_courses_test.txt --skip-download"
alias yta="youtube-dl -f bestvideo+bestaudio --write-auto-sub"
alias ytrl1k="youtube-dl -f bestvideo+bestaudio --write-auto-sub --cookies=~/Documents/cookies_youtube_rl1k.txt"
alias ytcourses="youtube-dl -f bestvideo+bestaudio --write-auto-sub --cookies=~/Documents/cookies_youtube_courses_test.txt"
alias ytpj="youtube-dl -f bestvideo+bestaudio --write-auto-sub --cookies=~/Documents/cookies_youtube_pj.txt"
alias tmuxks="tmux kill-session -t"
alias gui="xdg-open ."
alias msfupdate="sudo msfupdate"
#alias empire="sudo empire"
alias mysql="sudo mysql"
alias systemctl="sudo systemctl"
alias tor-browser="tor-browser-en"
alias tor="sudo tor"
alias aquatone-screenshot="aquatone -out /home/rl1k/Documents/aquatone-screenshots && google /home/rl1k/Documents/aquatone/aquatone_report.html"
#alias hashcat="optirun hashcat"
alias word="libreoffice --writer"

#SYMFONY
alias symfstop="php bin/console serve:stop"
alias symfstart="php bin/console serve:start"
alias cache="php bin/console c:c"
alias symf="php bin/console"
alias docup="php bin/console doctrine:schema:update --force"
alias docreate="php bin/console doctrine:schema:create"

alias symf4start="php bin/console server:start"
alias symf4stop="php bin/console server:stop"

